import React from 'react';
import {ArrowLeft,ArrowRight,CheckCircle2,Building2,Users,Workflow,Plug,Zap,BrainCircuit,Target} from 'lucide-react';

type Answers=Record<string,string>;
const steps=[
 {title:'Empresa e responsável',icon:Building2,fields:[['empresa','Nome da empresa','text',true],['nome','Seu nome','text',true],['cargo','Cargo ou função','text',true],['email','E-mail','email',true],['whatsapp','WhatsApp','tel',true],['segmento','Segmento da empresa','text',true],['cidade','Cidade / UF','text',false]]},
 {title:'O problema',icon:Target,fields:[['problema','Qual problema você quer resolver com o sistema?','textarea',true],['processo_atual','Como esse processo funciona atualmente? Descreva do início ao fim.','textarea',true],['dificuldades','Quais são as maiores dificuldades hoje?','textarea',true],['resultado','Se o sistema estivesse pronto hoje, o que ele precisaria resolver para o projeto ser um sucesso?','textarea',true]]},
 {title:'Usuários e acessos',icon:Users,fields:[['usuarios','Quem utilizará o sistema e aproximadamente quantas pessoas?','textarea',true],['perfis','Existem tipos diferentes de usuários (administrador, gestor, funcionário, cliente)? O que cada um precisa fazer ou visualizar?','textarea',false],['dispositivos','Onde o sistema será usado? Computador, celular, tablet ou todos?','text',true]]},
 {title:'Funcionalidades',icon:Workflow,fields:[['funcionalidades','Liste tudo o que você gostaria de conseguir fazer dentro do sistema.','textarea',true],['prioridades','Quais funcionalidades são indispensáveis na primeira versão?','textarea',true],['dados','Quais informações, cadastros ou documentos o sistema precisa armazenar?','textarea',false],['dashboard','Quais indicadores ou relatórios você gostaria de acompanhar?','textarea',false]]},
 {title:'Integrações e automações',icon:Plug,fields:[['ferramentas','Quais ferramentas vocês usam hoje? Ex.: Excel, Google Sheets, WhatsApp, ERP, CRM.','textarea',false],['integracoes','O novo sistema precisa se integrar com alguma ferramenta ou sistema?','textarea',false],['automacoes','Quais tarefas repetitivas você gostaria que acontecessem automaticamente?','textarea',false],['ia','Gostaria de usar Inteligência Artificial? Se sim, em quais atividades?','textarea',false]]},
 {title:'Projeto e prazo',icon:Zap,fields:[['dados_existentes','Existem planilhas, formulários ou dados que precisarão ser migrados?','textarea',false],['prazo','Existe uma data desejada ou obrigatória para colocar o sistema em operação?','text',false],['referencia','Existe algum sistema que você usa como referência?','text',false],['observacoes','Há alguma regra da operação ou informação adicional que precisamos conhecer?','textarea',false]]}
] as const;

export default function Diagnostico(){
 const[step,setStep]=React.useState(0);const[a,setA]=React.useState<Answers>({});const[sending,setSending]=React.useState(false);const[done,setDone]=React.useState(false);const[error,setError]=React.useState('');
 const current=steps[step]; const update=(k:string,v:string)=>setA(x=>({...x,[k]:v}));
 const valid=current.fields.filter(f=>f[3]).every(f=>(a[f[0]]||'').trim());
 async function next(){if(!valid)return;if(step<steps.length-1){setStep(step+1);window.scrollTo({top:0,behavior:'smooth'});return}setSending(true);setError('');try{const r=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nome:a.nome,empresa:a.empresa,cargo:a.cargo,whatsapp:a.whatsapp,email:a.email,processo:a.problema,origem:'Diagnóstico Wuniflow',pagina:window.location.href,diagnostico:a})});if(!r.ok)throw new Error();setDone(true)}catch{setError('Não foi possível enviar agora. Tente novamente em alguns instantes.')}finally{setSending(false)}}
 if(done)return <div className="diagPage"><div className="diagShell diagDone"><div className="diagLogo"><b>W</b><span>WUNIFLOW<small>AUTOMATIONS</small></span></div><CheckCircle2/><h1>Diagnóstico recebido.</h1><p>Obrigado, {a.nome}. As informações foram registradas e serão analisadas pela Wuniflow. Entraremos em contato para validar o cenário e os próximos passos.</p><a href="/">Voltar para a Wuniflow</a></div></div>;
 const Icon=current.icon;return <div className="diagPage"><header className="diagHeader"><a className="diagLogo" href="/"><b>W</b><span>WUNIFLOW<small>AUTOMATIONS</small></span></a><a href="/">Voltar ao site</a></header><main className="diagShell"><div className="diagIntro"><span>DIAGNÓSTICO DE PROJETO</span><h1>Vamos entender o sistema que sua empresa precisa.</h1><p>Responda com a realidade da sua operação. Você não precisa conhecer termos técnicos — queremos entender o problema, o processo e o resultado esperado.</p></div><div className="diagProgress"><div><span>Etapa {step+1} de {steps.length}</span><b>{Math.round(((step+1)/steps.length)*100)}%</b></div><i><em style={{width:`${((step+1)/steps.length)*100}%`}}/></i></div><section className="diagCard"><div className="diagCardTitle"><Icon/><div><small>ETAPA {String(step+1).padStart(2,'0')}</small><h2>{current.title}</h2></div></div><div className="diagFields">{current.fields.map(f=><label key={f[0]}>{f[1]}{f[3]&&<sup>*</sup>}{f[2]==='textarea'?<textarea rows={4} value={a[f[0]]||''} onChange={e=>update(f[0],e.target.value)} placeholder="Digite sua resposta..."/>:<input type={f[2]} value={a[f[0]]||''} onChange={e=>update(f[0],e.target.value)} placeholder="Digite sua resposta..."/>}</label>)}</div>{error&&<p className="diagError">{error}</p>}<div className="diagActions"><button className="diagBack" disabled={step===0||sending} onClick={()=>setStep(step-1)}><ArrowLeft/> Voltar</button><button className="diagNext" disabled={!valid||sending} onClick={next}>{sending?'Enviando...':step===steps.length-1?'Enviar diagnóstico':<>Continuar <ArrowRight/></>}</button></div></section><div className="diagTrust"><BrainCircuit/><span>Suas respostas serão usadas pela Wuniflow para compreender o escopo. Nenhum valor ou desenvolvimento é aprovado automaticamente.</span></div></main></div>
}