import React from 'react';
import {ArrowLeft,ArrowRight,CheckCircle2,Building2,Users,Workflow,Plug,Zap,BrainCircuit,Target,Download} from 'lucide-react';

type Answers=Record<string,string>;
const steps=[
 {title:'Empresa e responsável',icon:Building2,fields:[['empresa','Nome da empresa','text',true],['nome','Seu nome','text',true],['cargo','Cargo ou função','text',true],['email','E-mail','email',true],['whatsapp','WhatsApp','tel',true],['segmento','Segmento da empresa','text',true],['cidade','Cidade / UF','text',false]]},
 {title:'O problema',icon:Target,fields:[['problema','Qual problema você quer resolver com o sistema?','textarea',true],['processo_atual','Como esse processo funciona atualmente? Descreva do início ao fim.','textarea',true],['dificuldades','Quais são as maiores dificuldades hoje?','textarea',true],['resultado','Se o sistema estivesse pronto hoje, o que ele precisaria resolver para o projeto ser um sucesso?','textarea',true]]},
 {title:'Usuários e acessos',icon:Users,fields:[['usuarios','Quem utilizará o sistema e aproximadamente quantas pessoas?','textarea',true],['perfis','Existem tipos diferentes de usuários (administrador, gestor, funcionário, cliente)? O que cada um precisa fazer ou visualizar?','textarea',false],['dispositivos','Onde o sistema será usado? Computador, celular, tablet ou todos?','text',true]]},
 {title:'Funcionalidades',icon:Workflow,fields:[['funcionalidades','Liste tudo o que você gostaria de conseguir fazer dentro do sistema.','textarea',true],['prioridades','Quais funcionalidades são indispensáveis na primeira versão?','textarea',true],['dados','Quais informações, cadastros ou documentos o sistema precisa armazenar?','textarea',false],['dashboard','Quais indicadores ou relatórios você gostaria de acompanhar?','textarea',false]]},
 {title:'Integrações e automações',icon:Plug,fields:[['ferramentas','Quais ferramentas vocês usam hoje? Ex.: Excel, Google Sheets, WhatsApp, ERP, CRM.','textarea',false],['integracoes','O novo sistema precisa se integrar com alguma ferramenta ou sistema?','textarea',false],['automacoes','Quais tarefas repetitivas você gostaria que acontecessem automaticamente?','textarea',false],['ia','Gostaria de usar Inteligência Artificial? Se sim, em quais atividades?','textarea',false]]},
 {title:'Projeto e prazo',icon:Zap,fields:[['dados_existentes','Existem planilhas, formulários ou dados que precisarão ser migrados?','textarea',false],['prazo','Existe uma data desejada ou obrigatória para colocar o sistema em operação?','text',false],['referencia','Existe algum sistema que você usa como referência?','text',false],['observacoes','Há alguma regra da operação ou informação adicional que precisamos conhecer?','textarea',false]]}
] as const;

export default function Diagnostico(){
 const[step,setStep]=React.useState(0);const[a,setA]=React.useState<Answers>({});const submissionId=React.useRef(crypto.randomUUID());const[sending,setSending]=React.useState(false);const[done,setDone]=React.useState(false);const[error,setError]=React.useState('');const[consent,setConsent]=React.useState(false);const[projectId,setProjectId]=React.useState('');
 const downloadBriefing=()=>{const sections=[
 ['1. IDENTIFICAÇÃO DA EMPRESA',[['Empresa','empresa'],['Responsável','nome'],['Cargo / função','cargo'],['E-mail','email'],['WhatsApp','whatsapp'],['Segmento','segmento'],['Cidade / UF','cidade']]],
 ['2. NECESSIDADE E CENÁRIO ATUAL',[['Problema a resolver','problema'],['Processo atual','processo_atual'],['Principais dificuldades','dificuldades'],['Resultado esperado','resultado']]],
 ['3. USUÁRIOS E ACESSOS',[['Usuários','usuarios'],['Perfis e permissões','perfis'],['Dispositivos','dispositivos']]],
 ['4. FUNCIONALIDADES E DADOS',[['Funcionalidades desejadas','funcionalidades'],['Prioridades do MVP','prioridades'],['Dados e cadastros','dados'],['Dashboard e relatórios','dashboard']]],
 ['5. INTEGRAÇÕES, AUTOMAÇÕES E IA',[['Ferramentas atuais','ferramentas'],['Integrações','integracoes'],['Automações','automacoes'],['Inteligência Artificial','ia']]],
 ['6. PROJETO E PRAZO',[['Dados existentes / migração','dados_existentes'],['Prazo','prazo'],['Referências','referencia'],['Observações adicionais','observacoes']]]
 ] as const;const esc=(v:string)=>String(v||'Não informado').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]||m)).replace(/\n/g,'<br>');const html=`<!doctype html><html><head><meta charset="utf-8"><title>Briefing Wuniflow - ${esc(a.empresa)}</title><style>@page{size:A4;margin:16mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#18121a;margin:0;font-size:11pt;line-height:1.5}header{border-bottom:3px solid #d600e9;padding-bottom:14px;margin-bottom:28px}header b{font-size:24px;letter-spacing:2px}header span{display:block;color:#d600e9;font-weight:bold;font-size:9px;letter-spacing:2px;margin-top:3px}h1{font-size:24px;margin:0 0 6px}h2{font-size:13px;color:#a600b6;border-bottom:1px solid #e9ddea;padding-bottom:6px;margin:24px 0 12px}.meta{color:#6e6370;font-size:9px;margin-bottom:25px}.item{margin:0 0 12px;break-inside:avoid}.item strong{display:block;font-size:9px;text-transform:uppercase;letter-spacing:.6px;color:#6e6370;margin-bottom:3px}.item div{background:#f7f4f8;border-left:2px solid #d600e9;padding:9px 11px}.note{margin-top:28px;padding:12px;background:#100d11;color:#fff;font-size:9px}.note b{color:#ef2cff}footer{margin-top:22px;color:#8b818d;font-size:8px;text-align:center}</style></head><body><header><b>WUNIFLOW</b><span>AUTOMATIONS</span></header><h1>Briefing de Descoberta do Projeto</h1><div class="meta">Documento gerado a partir das respostas fornecidas pelo cliente em ${new Date().toLocaleDateString('pt-BR')}.</div>${sections.map(([title,items])=>`<h2>${title}</h2>${items.map(([label,key])=>`<div class="item"><strong>${label}</strong><div>${esc(a[key])}</div></div>`).join('')}`).join('')}<div class="note"><b>IMPORTANTE</b><br>Este documento registra as respostas originais do cliente e não representa ainda escopo técnico, orçamento, prazo contratual ou aprovação de desenvolvimento. A análise técnica e comercial da Wuniflow deve ser validada separadamente.</div><footer>WUNIFLOW AUTOMATIONS - Sistemas • Automação • Inteligência Artificial • Cloud - www.wuniflow.site</footer></body></html>`;const w=window.open('','_blank');if(!w)return;w.document.write(html);w.document.close();setTimeout(()=>w.print(),300)};
 const current=steps[step]; const update=(k:string,v:string)=>setA(x=>({...x,[k]:v}));
 const valid=current.fields.filter(f=>f[3]).every(f=>(a[f[0]]||'').trim());
 async function next(){if(!valid||(step===steps.length-1&&!consent))return;if(step<steps.length-1){setStep(step+1);window.scrollTo({top:0,behavior:'smooth'});return}setSending(true);setError('');try{const r=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nome:a.nome,empresa:a.empresa,cargo:a.cargo,whatsapp:a.whatsapp,email:a.email,processo:a.problema,origem:'Diagnóstico Wuniflow',pagina:window.location.href,website:'',submissionId:submissionId.current,diagnostico:a,consentimento:{aceito:true,versao:'diagnostico-v1',texto:'Autorizo a Wuniflow a utilizar as informações deste diagnóstico para analisar minha solicitação e entrar em contato sobre este projeto.'}})});if(!r.ok)throw new Error();const data=await r.json();setProjectId(data.projectId||'');setDone(true)}catch{setError('Não foi possível enviar agora. Tente novamente em alguns instantes.')}finally{setSending(false)}}
 if(done)return <div className="diagPage"><div className="diagShell diagDone"><div className="diagLogo"><b>W</b><span>WUNIFLOW<small>AUTOMATIONS</small></span></div><CheckCircle2/><h1>Diagnóstico recebido.</h1><p>Obrigado, {a.nome}. As informações foram registradas e serão analisadas pela Wuniflow. Entraremos em contato para validar o cenário e os próximos passos.</p>{projectId&&<div className="diagProjectId"><small>IDENTIFICAÇÃO DO PROJETO</small><b>{projectId}</b></div>}<div className="diagDoneActions"><button onClick={downloadBriefing}><Download/> Gerar PDF do briefing</button><a href="/">Voltar para a Wuniflow</a></div></div></div>;
 const Icon=current.icon;return <div className="diagPage"><header className="diagHeader"><a className="diagLogo" href="/"><b>W</b><span>WUNIFLOW<small>AUTOMATIONS</small></span></a><a href="/">Voltar ao site</a></header><main className="diagShell"><div className="diagIntro"><span>DIAGNÓSTICO DE PROJETO</span><h1>Vamos entender o sistema que sua empresa precisa.</h1><p>Responda com a realidade da sua operação. Você não precisa conhecer termos técnicos — queremos entender o problema, o processo e o resultado esperado.</p></div><div className="diagProgress"><div><span>Etapa {step+1} de {steps.length}</span><b>{Math.round(((step+1)/steps.length)*100)}%</b></div><i><em style={{width:`${((step+1)/steps.length)*100}%`}}/></i></div><section className="diagCard"><div className="diagCardTitle"><Icon/><div><small>ETAPA {String(step+1).padStart(2,'0')}</small><h2>{current.title}</h2></div></div><div className="diagFields">{current.fields.map(f=><label key={f[0]}>{f[1]}{f[3]&&<sup>*</sup>}{f[2]==='textarea'?<textarea rows={4} value={a[f[0]]||''} onChange={e=>update(f[0],e.target.value)} placeholder="Digite sua resposta..."/>:<input type={f[2]} value={a[f[0]]||''} onChange={e=>update(f[0],e.target.value)} placeholder="Digite sua resposta..."/>}</label>)}</div>{step===steps.length-1&&<label className="diagConsent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>Autorizo a Wuniflow a utilizar as informações deste diagnóstico para analisar minha solicitação e entrar em contato sobre este projeto. <b>*</b></span></label>}{error&&<p className="diagError">{error}</p>}<div className="diagActions"><button className="diagBack" disabled={step===0||sending} onClick={()=>setStep(step-1)}><ArrowLeft/> Voltar</button><button className="diagNext" disabled={!valid||sending||(step===steps.length-1&&!consent)} onClick={next}>{sending?'Enviando...':step===steps.length-1?'Enviar diagnóstico':<>Continuar <ArrowRight/></>}</button></div></section><div className="diagTrust"><BrainCircuit/><span>Suas respostas serão usadas pela Wuniflow para compreender o escopo. Nenhum valor ou desenvolvimento é aprovado automaticamente.</span></div></main></div>
}